import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { AuthProvider } from '/context/AuthContext';
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <AppRouterCacheProvider options={{ key: 'css' }}>
            {children}
            <Toaster position="bottom-center"
              containerStyle={{ bottom: "10%" }}
              toastOptions={{
                style: {
                  borderRadius: "5px",
                  padding: "16px 24px"
                }
              }} />
          </AppRouterCacheProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
